name: 'AWS Secrets Manager Action'
author: 'Abhilash Kishore'
description: 'Use secrets from AWS Secrets Manager as environment variables in your GitHub Actions workflow'
inputs:
  secrets:
    description: 'List of secret names you want to fetch secret values for'
    required: true
  parse-json:
    description: 'If true and secret values are stringified JSON objects, they will be parsed and flattened. Its key value pairs will become individual secrets'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
